### ISSUE TITLE
Windows上运行需要什么依赖配置吗？

### ISSUE THREAD

**Issue by 3-years-Czech** [nICEnnnnnnnLee/LiveRecorder#13]
当我运行这条指令时：you-live -check douyu 5110403
产生了这样的报错
Traceback (most recent call last):                                                                                        
File "d:\anaconda\lib\runpy.py", line 194, in _run_module_as_main                                                         
return _run_code(code, main_globals, None,                                                                            
File "d:\anaconda\lib\runpy.py", line 87, in _run_code                                                                    
exec(code, run_globals)                                                                                               
File "D:\Anaconda\Scripts\you-live.exe\__main__.py", line 7, in <module>                                                
File "d:\anaconda\lib\site-packages\live_recorder\__main__.py", line 52, in main                                          
roomInfo = recorder.getRoomInfo()                                                                                     
File "d:\anaconda\lib\site-packages\live_recorder\you_live\douyu_recorder.py", line 77, in getRoomInfo                    
param = ctx.call("ub98484234", roomInfo['room_id'], self.dy_did, int(time.time()))                                    
File "d:\anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call                                
return self._call(name, *args)                                                                                        
File "d:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 92, in _call                                       
return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))                        
File "d:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval                                       
return self.exec_(code)                                                                                               
File "d:\anaconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_                               
return self._exec_(source)                                                                                            
File "d:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_                                      
return self._extract_result(output)                                                                                   
File "d:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result                            
raise ProgramError(value)                                                                                           
execjs._exceptions.ProgramError: TypeError: 缺少对象

**Comment by nICEnnnnnnnLee** [comment]
douyu解析需要调用js，这里引入了[PyExecJS](https://github.com/doloopwhile/PyExecJS)(虽然PyExecJS不再维护)。

它的优势就在于，**The pros of PyExecJS is that you do not need take care of JavaScript environment. Especially, it works in Windows environment without installing extra libraries.**

理论上来说不需要额外依赖。

你可以先测试一下你的环境下PyExecJS 的简单用例是否能正常运行

**Comment by davidxxxxx** [comment]
同一个问题，PyExecJS似乎运行不了，有什么解决方案吗

edit: 安装了node.js 好像问题解决了
