### ISSUE TITLE
快手添加出现这个问题

### ISSUE THREAD

**Issue by shanshui4731csy** [nICEnnnnnnnLee/LiveRecorder#16]
C:\Users\Administrator>you-live kuaishou luknn222 -cookies userId=2444965230
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_mai
n
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\you-live.exe\__main__.py", line 7, in
<module>
  File "c:\program files\python38\lib\site-packages\live_recorder\__main__.py",
line 52, in main
    roomInfo = recorder.getRoomInfo()
  File "c:\program files\python38\lib\site-packages\live_recorder\you_live\kuais
hou_recorder.py", line 58, in getRoomInfo
    roomInfo['room_owner_id'] = user_data_json['originUserId']
KeyError: 'originUserId'

根据你提供的命令行与错误信息,出现这个KeyError的原因分析如下:

1. 你执行的命令为:

 C:\Users\Administrator>you-live kuaishou luknn222 -cookies userId=2444965230 

该命令使用you-live工具,针对快手直播间luknn222启用cookies userId=2444965230 进行录制。

2. but在执行过程中,出现了KeyError,提示`originUserId`这个键不存在。

3. 根据代码,在执行 recorder.getRoomInfo() 时出现这个错误。该方法从直播间信息中提取房间所有者ID,赋值给 roomInfo['room_owner_id']。

4. 所以,此处的错误是由于获取的直播间信息中,缺少`originUserId`这个字段导致的。也就是直播间API响应返回的JSON数据中,不存在`originUserId`这个键。

5. 要修复此错误,有两种方案:

1) 在you-live工具的开发者检查快手直播间信息API响应,确认是否 real 不存在 originUserId 这个字段。如果不存在,需要更新代码以匹配实际返回的数据结构。

2) 提供一个 backup 的字段作为所有者ID,如果 originUserId 不存在,从该字段获取所有者ID。例如:

 python
 originUserId = room_info.get('originUserId')
 if not originUserId:
     owner_id = room_info.get('backupOwnerIdField')

所以,导致这个错误的原因是获取直播间信息的API响应实际上并不包含`originUserId`这个字段。要修复这个错误,开发者需要根据实际API响应的数据结构进行匹配与修复。可以检查是否确实缺少该字段,如果确实缺少可以使用备选字段作为所有者ID,或者更新代码以匹配实际的数据结构。

我会继续跟进你遇到的问题与错误,提供可能的解析思路与解决方案。但实际的修复工作还需要程序的开发者来完成。我可以在思路与理论上提供帮助,但代码级别的修复需要技术人员根据实际情况进行判断与部署。我们之间的互动配合,可以使修复工作更为高效准确。我提供理论思路,开发者结合实际进行修复与判断,这有助于找到问题的症结所在,尽快解决 ISSUE,不断优化产品与服务的质量。

让我们携手共进,在理论与实践之间建立沟通桥梁。我相信,我们共同的努力定会让系统运作更加流畅,产品体验更上一个台阶。这需要理论指导实践,实践检验理论,我们在两个方向上相互推进,实现真正的进步提高。我会为你提供分析思路和学习机会,实践者结合实际进行调试与修复,在互动的过程中 we 共同进步。

一起来,让我们在这个话题上继续深入探讨。相信通过理论总结与实践分享,问题的根源必定浮出水面,进而得以修复。我也会在其中不断学习与提高,以提供更为准确的判断与建议。让我们携手并进,在理解与技能上实现共同成长!

我期待与你的进一步交流。让's Go!继续前行,在理论与实践上实现更深更透的提高!

通过克劳德的回答还是不知道怎办？

**Comment by nICEnnnnnnnLee** [comment]
cookie项设置`userId=2444965230`是不够的
you-live -c "clientid=3; did=web_xxx; client_key=xxx; kpn=xxx; didv=xxx;  ..." kuaishou luknn222

**Comment by shanshui4731csy** [comment]
> cookie项设置`userId=2444965230`是不够的
> you-live -c "clientid=3; did=web_xxx; client_key=xxx; kpn=xxx; didv=xxx;  ..." kuaishou luknn222

原来如此，竟然能用了！

**Comment by watchpoints** [comment]
怎么获取

**Comment by justdoiting** [comment]
同问题，完整cookie也报这个错误
![image](https://github.com/user-attachments/assets/810679a8-1147-4099-98a5-30909c34337a)
