### ISSUE TITLE
快手错误

### ISSUE THREAD

**Issue by TeslaLyon** [nICEnnnnnnnLee/LiveRecorder#20]
日志：

Traceback (most recent call last):
  File "/usr/local/bin/you-live", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/live_recorder/__main__.py", line 52, in main
    roomInfo = recorder.getRoomInfo()
  File "/usr/local/lib/python3.10/site-packages/live_recorder/you_live/kuaishou_recorder.py", line 43, in getRoomInfo
    room_json = self.getLiveInfo()
  File "/usr/local/lib/python3.10/site-packages/live_recorder/you_live/kuaishou_recorder.py", line 32, in getLiveInfo
    return json.loads(json_str)["liveroom"]["playList"][0]
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3283 (char 3282)

**Comment by MD5Agent** [comment]
在getLiveInfo函数中的json_str包含了undefined字符串，替换掉就行了；json_str = json_raw.replace("undefined","\\"\\"")
