### ISSUE TITLE
B站录制失败

### ISSUE THREAD

**Issue by KNulL0** [nICEnnnnnnnLee/LiveRecorder#6]
Traceback (most recent call last):
  File "/usr/bin/you-live", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/live_recorder/__main__.py", line 52, in main
    roomInfo = recorder.getRoomInfo()
  File "/usr/lib/python3.9/site-packages/live_recorder/you_live/bili_recorder.py", line 26, in getRoomInfo
    data_json = requests.get(url, timeout=10, headers=headers).json()['data']
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

**Comment by iwestlin** [comment]
https://github.com/nICEnnnnnnnLee/LiveRecorder/pull/7/files 这个PR可以修复

**Comment by nICEnnnnnnnLee** [comment]
这个没来得及更新。。。

问题主要是header里面带了`Accept-Encoding': 'gzip, deflate, br`，
然后现在B站返回的encoding基本不用`gzip`用`br`了，
然后`requests`包只支持`gzip`的decoding，
然后内容就会是乱码，
然后报错。

注掉这个不用，或者改为`'Accept-Encoding': 'gzip'`都可以
